"""Extract the M22 review workflow state from the Workflow-tool journals.

Re-runnable. Run it at the START of the next session before continuing, because the
four workflows may have produced more results after the snapshot committed here.

    python docs/investigations/2026-09-06-full-review-state/extract_state.py \
        --journals "C:/Users/SynAckITPC/.claude/projects/C--Users-SynAckITPC-Documents-AI/f110259b-2c46-4d36-b8fd-39f57a9eb840/subagents/workflows" \
        --out docs/investigations/2026-09-06-full-review-state

Outputs, per workflow NAME in RUNS below:
  partial-<name>.json        {lanes:{key:finder_result}, verdicts:{id:first_verdict}, second_votes:{id:verdict},
                              synth: {...}|null, critic: {...}|null, tally: {...}}
  continue-args-<name>.json  ready-to-paste `args` for m22_review_continue.js (merges args-<name>.json)
  STATE_SUMMARY.md           human summary of what is done / missing

Journal rows carry no labels, so results are classified by SHAPE:
  {lane, findings, coverage, not_covered}  -> finder lane result
  {verdicts:[...]}                          -> batch verifier (flattened into verdicts)
  {id, verdict, ...} first time for an id   -> first-stage verifier
  {id, verdict, ...} second time for an id  -> second vote (the original script only runs vote2 after ALL verifies)
  {report_md, ...}                          -> synthesis
  {gaps, ...}                               -> completeness critic
"""
from __future__ import annotations

import argparse
import collections
import json
import os
import sys

RUNS = {
    "m22-product-output": "wf_4127a8d5-5b2",
    "m22-code-review": "wf_cbda6ac4-a50",
    "m22-load-scale": "wf_46983729-4eb",
    "m22-mobile": "wf_e23aeca8-908",
}


def load_rows(path: str):
    rows = []
    if not os.path.exists(path):
        return rows
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            try:
                rows.append(json.loads(line))
            except Exception:
                continue
    return rows


def extract(journal_path: str):
    lanes, verdicts, second, synth, critic = {}, {}, {}, None, None
    started = failed = 0
    for e in load_rows(journal_path):
        t = e.get("type")
        if t == "started":
            started += 1
        elif t == "failed":
            failed += 1
        if t != "result":
            continue
        r = e.get("result")
        if not isinstance(r, dict):
            continue
        if "lane" in r and "findings" in r:
            lanes[r["lane"]] = r
        elif "verdicts" in r and isinstance(r["verdicts"], list):
            for v in r["verdicts"]:
                if isinstance(v, dict) and "id" in v:
                    if v["id"] in verdicts:
                        second[v["id"]] = v
                    else:
                        verdicts[v["id"]] = v
        elif "id" in r and "verdict" in r:
            if r["id"] in verdicts:
                second[r["id"]] = r
            else:
                verdicts[r["id"]] = r
        elif "report_md" in r:
            synth = r
        elif "gaps" in r:
            critic = r
    return lanes, verdicts, second, synth, critic, started, failed


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--journals", required=True, help="dir containing wf_*/journal.jsonl")
    ap.add_argument("--out", required=True, help="state dir (holds args-<name>.json)")
    a = ap.parse_args()

    summary = ["# M22 review — state summary (generated by extract_state.py)", ""]
    for name, wf in RUNS.items():
        jp = os.path.join(a.journals, wf, "journal.jsonl")
        lanes, verdicts, second, synth, critic, started, failed = extract(jp)
        args_path = os.path.join(a.out, f"args-{name}.json")
        args = json.load(open(args_path, encoding="utf-8")) if os.path.exists(args_path) else {}
        all_lanes = [l["key"] for l in args.get("lanes", [])]
        missing = [k for k in all_lanes if k not in lanes]
        findings = [dict(f, lane=k) for k, v in lanes.items() for f in v.get("findings", [])]
        fmap = {f["id"]: f for f in findings}
        unverified = [{"id": f["id"], "lane": f["lane"], "sev": f["sev"]} for f in findings if f["id"] not in verdicts]
        survivors = []
        for fid, v in verdicts.items():
            if v.get("verdict") == "REFUTED":
                continue
            sev = v.get("sev_after") or fmap.get(fid, {}).get("sev")
            if sev in ("P0", "P1") and fid not in second:
                survivors.append({"id": fid, "lane": fmap.get(fid, {}).get("lane", fid.rsplit("-", 1)[0].lower()), "sev": sev})
        tally = collections.Counter()
        for fid, v in verdicts.items():
            if v.get("verdict") == "REFUTED":
                tally["REFUTED"] += 1
            else:
                sv = second.get(fid)
                sev = (sv.get("sev_after") if sv and sv.get("verdict") in ("DOWNGRADED", "UPGRADED") else None) or v.get("sev_after") or fmap.get(fid, {}).get("sev")
                if sv and sv.get("verdict") == "REFUTED":
                    tally["REFUTED-2nd"] += 1
                else:
                    tally[sev] += 1
        state = {
            "name": name, "run_id": wf, "journal": jp, "base": "76ace90",
            "lanes": lanes, "verdicts": verdicts, "second_votes": second, "synth": synth, "critic": critic,
            "tally": dict(tally), "counts": {"started": started, "failed": failed, "lanes_done": len(lanes), "lanes_all": len(all_lanes),
                                              "filed": len(findings), "verified": len(verdicts), "unverified": len(unverified), "second_votes": len(second)},
            "missing_lanes": missing, "unverified": unverified, "p0p1_needing_second_vote": survivors,
        }
        with open(os.path.join(a.out, f"partial-{name}.json"), "w", encoding="utf-8") as fh:
            json.dump(state, fh, indent=1, ensure_ascii=False)
        cont = dict(args)
        cont.update({
            "stateFile": os.path.abspath(os.path.join(a.out, f"partial-{name}.json")).replace("\\", "/"),
            "reviewNotes": os.path.abspath(os.path.join(a.out, "FABLE_REVIEW_NOTES.md")).replace("\\", "/"),
            "missingLanes": missing, "unverified": unverified, "secondVote": survivors,
            "haveSynth": synth is not None, "haveCritic": critic is not None,
        })
        with open(os.path.join(a.out, f"continue-args-{name}.json"), "w", encoding="utf-8") as fh:
            json.dump(cont, fh, indent=1, ensure_ascii=False)
        summary.append(f"## {name} ({wf})")
        summary.append(f"- lanes done {len(lanes)}/{len(all_lanes)}; MISSING: {missing or 'none'}")
        summary.append(f"- filed {len(findings)}; first-verified {len(verdicts)}; unverified {len(unverified)}; second votes {len(second)}; synth {'yes' if synth else 'NO'}; critic {'yes' if critic else 'NO'}")
        summary.append(f"- tally after verification: {dict(tally)}")
        summary.append(f"- P0/P1 still needing a second vote: {[s['id'] for s in survivors]}")
        summary.append("")
    with open(os.path.join(a.out, "STATE_SUMMARY.md"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(summary))
    sys.stdout.reconfigure(encoding="utf-8")
    print("\n".join(summary))


if __name__ == "__main__":
    main()
