"""Render the per-severity findings tables + the refuted/downgraded ledger from the verified JSON.

    python docs/investigations/2026-09-06-full-review-state/render_tables.py \
        --json docs/investigations/2026-09-06-full-review-verified.json \
        --out docs/investigations/2026-09-06-full-review-tables.md
"""
from __future__ import annotations

import argparse
import collections
import json
import sys


def esc(t):
    return (t or "").replace("|", "\\|").replace("\n", " ").strip()


def short(t, n):
    t = esc(t)
    return t if len(t) <= n else t[: n - 1] + "…"


def trail(row):
    parts = []
    for t in row.get("verdict_trail") or []:
        parts.append(f"{t['stage'][:6]}:{t.get('verdict','?')}→{t.get('sev_after','?')}")
    f = row.get("fable")
    if f:
        parts.append("fable:" + f["verdict"])
    return " · ".join(parts) or "filed only"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--json", required=True)
    ap.add_argument("--out", required=True)
    a = ap.parse_args()
    d = json.load(open(a.json, encoding="utf-8"))
    rows = d["findings"]
    cluster_lead = {}
    for c in d.get("dedupe_clusters", []):
        for fid in c:
            cluster_lead.setdefault(fid, c[0])

    L = [f"# Findings tables — {d['review']} (base `{d['base']}`)", "",
         f"Generated by `render_tables.py` from `{a.json.split('/')[-1]}` on the SESSION 65 continuation. "
         "Verdict trail = first verifier → second vote → Fable. A row whose `dedupe` names another id is the SAME defect reported by another lane (kept for the audit trail; count once).", ""]

    tally = collections.Counter()
    for r in rows:
        if r["status"] == "verified":
            tally[r["sev_final"]] += 1
        else:
            tally[r["status"].upper()] += 1
    L.append("**Tally (after both verification stages + Fable, before dedupe):** " + ", ".join(f"{k} {v}" for k, v in sorted(tally.items())) + ".")
    per_wf = collections.defaultdict(collections.Counter)
    for r in rows:
        per_wf[r["workflow"]][r["sev_final"] if r["status"] == "verified" else r["status"].upper()] += 1
    L.append("")
    L.append("| workflow | " + " | ".join(["P0", "P1", "P2", "P3", "REFUTED", "other"]) + " |")
    L.append("|---|---|---|---|---|---|---|")
    for wf, c in per_wf.items():
        other = sum(v for k, v in c.items() if k not in ("P0", "P1", "P2", "P3", "REFUTED"))
        L.append(f"| {wf} | {c.get('P0',0)} | {c.get('P1',0)} | {c.get('P2',0)} | {c.get('P3',0)} | {c.get('REFUTED',0)} | {other} |")
    L.append("")

    for sev in ("P0", "P1", "P2", "P3"):
        sel = [r for r in rows if r["status"] == "verified" and r["sev_final"] == sev]
        sel.sort(key=lambda r: (r["workflow"], r["id"]))
        L.append(f"## {sev} — {len(sel)} rows")
        L.append("")
        L.append("| id | title | file:line | M/M | verdict trail | dedupe / cluster |")
        L.append("|---|---|---|---|---|---|")
        for r in sel:
            dd = short(r.get("dedupe"), 60)
            cl = cluster_lead.get(r["id"])
            if cl and cl != r["id"]:
                dd = f"CLUSTER→{cl}; " + dd
            L.append(f"| {r['id']} | {short(r.get('title'), 110)} | `{esc(r.get('file'))}:{r.get('line')}` | {r.get('measured_or_modelled','?')[:8]} | {esc(trail(r))} | {dd} |")
        L.append("")

    L.append("## Refuted, downgraded, unverifiable — ledger")
    L.append("")
    L.append("| id | filed | final | what happened |")
    L.append("|---|---|---|---|")
    for r in sorted(rows, key=lambda r: (r["workflow"], r["id"])):
        changed = r["status"] != "verified" or r["sev_filed"] != r["sev_final"] or (r.get("fable") and r["fable"]["verdict"] not in ("DEDUPE",))
        if not changed:
            continue
        why = []
        for t in r.get("verdict_trail") or []:
            if t.get("verdict") in ("REFUTED", "DOWNGRADED", "UPGRADED", "UNVERIFIABLE"):
                why.append(f"{t['stage']}: {t['verdict']} — {short(t.get('reason'), 160)}")
        if r.get("fable"):
            why.append(f"Fable: {r['fable']['verdict']} — {short(r['fable']['note'], 160)}")
        L.append(f"| {r['id']} | {r['sev_filed']} | {r['sev_final'] if r['status']=='verified' else r['status'].upper()} | {' / '.join(why) or '—'} |")
    L.append("")
    open(a.out, "w", encoding="utf-8").write("\n".join(L))
    print("wrote", a.out, "rows", len(rows), dict(tally))


if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8")
    main()
