/**
 * Faithful-results Phase 2.2 (FE BUG #4) — runner-up caption un-suppression.
 *
 * The "where the runner-up wins" line is generated by the verdict prompt as
 * `overview.winner.key_tradeoff`. Before this fix it was rendered ONLY in the
 * else-branch of `scoring_v2.factual_verdict.line1`, so whenever a factual
 * verdict existed (≈ always) the runner-up case was silently dropped on the
 * Results screen. These tests pin the new contract: the winner verdict and the
 * runner-up caption are TWO ORTHOGONAL blocks — the caption renders whenever
 * `key_tradeoff` exists, regardless of whether a factual verdict is present.
 */

import React from 'react';
import { render } from '@testing-library/react-native';

jest.mock('react-native-reanimated', () => {
  const real = jest.requireActual('react-native-reanimated');
  const entering = { duration: () => entering, delay: () => entering };
  return {
    __esModule: true,
    ...real,
    default: real.default ?? real,
    FadeIn: entering,
    FadeInDown: entering,
  };
});

// i18n passthrough — `t(key)` returns the key so the runner-up eyebrow is
// assertable via its key string.
jest.mock('react-i18next', () => ({
  useTranslation: () => ({
    t: (key: string, opts?: Record<string, unknown>) => {
      let str = (opts?.defaultValue as string) ?? key;
      if (opts) {
        for (const [k, v] of Object.entries(opts)) {
          if (k === 'defaultValue') continue;
          str = str.replace(new RegExp(`\\{\\{${k}\\}\\}`, 'g'), String(v));
        }
      }
      return str;
    },
  }),
}));

// FactualVerdict renders a discoverable testID node so we can assert it
// coexists with the runner-up caption.
jest.mock('../../src/components/results/FactualVerdict', () => ({
  FactualVerdict: ({ testID, line1 }: any) => {
    const { View, Text } = require('react-native');
    return (
      <View testID={testID ?? 'mock-factual-verdict'}>
        <Text>{line1}</Text>
      </View>
    );
  },
}));
jest.mock('../../src/components/results/DimensionBars', () => ({
  DimensionBars: ({ testID }: any) => {
    const { View } = require('react-native');
    return <View testID={testID ?? 'mock-dim-bars'} />;
  },
}));
jest.mock('../../src/components/results/ConfidencePills', () => ({
  ConfidencePills: ({ testID }: any) => {
    const { View } = require('react-native');
    return <View testID={testID ?? 'mock-confidence-pills'} />;
  },
}));
jest.mock('../../src/components/results/ConfidenceDetailsSheet', () => ({
  ConfidenceDetailsSheet: () => null,
}));
jest.mock('../../src/components/results/PersonalizationChip', () => ({
  PersonalizationChip: () => null,
}));
jest.mock('../../src/components/results/TopMatchBadge', () => ({
  TopMatchBadge: () => null,
}));
jest.mock('../../src/components/hero/RevealBurst', () => ({ RevealBurst: () => null }));
jest.mock('../../src/components/CohortBadge', () => ({ CohortBadge: () => null }));
jest.mock('../../src/components/FeedbackCard', () => ({ __esModule: true, default: () => null }));
jest.mock('../../src/components/results/ResultsAccordion', () => ({
  ResultsAccordion: () => null,
}));
jest.mock('../../src/services/sourceMethod', () => ({ anyEstimated: jest.fn(() => false), isConvertedUsd: jest.fn((p: any) => p?.source_method === 'converted_usd') }));

import { ResultsContent } from '../../src/components/results/ResultsContent';

const products: any = [
  { name: 'iPhone 15', brand: 'Apple', price: { amount: 329, currency: 'BHD' } },
  { name: 'Galaxy S24', brand: 'Samsung', price: { amount: 299, currency: 'BHD' } },
];

const KEY_TRADEOFF = 'iPhone keeps the faster chip and tighter app ecosystem';

const baseScoringV2: any = {
  overall_score: { product_a: 72, product_b: 81 },
  dimensions: [
    { dim: 'camera', winner_index: 1 },
    { dim: 'battery', winner_index: 1 },
    { dim: 'price', winner_index: 0 },
  ],
  confidence_legs: { price: 'high', reviews: 'medium', specs: 'high' },
  factual_verdict: {
    line1: 'Galaxy S24 takes 4 of 6 dimensions',
    line2: 'Camera + battery hold the most weight',
  },
  personalization: { applied_shifts: [] },
  comparison_quality: 'normal',
  confidence_details: {},
};

const baseProps: any = {
  result: {
    overview: {
      winner: {
        product_index: 1,
        name: 'Galaxy S24',
        reason: 'Tuned to your priorities — camera + battery win',
        key_tradeoff: KEY_TRADEOFF,
      },
      products,
    },
    recommendation: 'Galaxy S24 wins on camera + battery',
  },
  products,
  winnerIndex: 1 as 0 | 1,
  scoring_v2: baseScoringV2,
  comparisonId: 'cmp-runner-up',
  cohortPeerCount: 0,
  cohortGovernorate: '',
  isRTL: false,
  feedbackSubmitted: false,
  onFeedbackSubmitted: jest.fn(),
  feedbackComparisonId: 'cmp-runner-up',
  sheetLeg: null,
  onPillPress: jest.fn(),
  onCloseSheet: jest.fn(),
  winnerRevealed: true,
  winnerScaleAnimStyle: { transform: [{ scale: 1 }] },
  onBack: jest.fn(),
  onShare: jest.fn(),
};

describe('ResultsContent — runner-up caption (Phase 2.2 FE BUG #4)', () => {
  it('renders BOTH the FactualVerdict AND the runner-up caption when both exist', () => {
    const { getByTestId, getByText } = render(<ResultsContent {...baseProps} />);
    // Winner verdict present.
    expect(getByTestId('results-content-factual-verdict')).toBeTruthy();
    // Runner-up case is no longer suppressed — eyebrow + key_tradeoff both show.
    expect(getByText('results.runnerUpWins')).toBeTruthy();
    expect(getByText(KEY_TRADEOFF)).toBeTruthy();
  });

  it('still shows the runner-up caption when there is NO factual verdict (recommendation fallback)', () => {
    const sv2 = { ...baseScoringV2, factual_verdict: undefined };
    const { queryByTestId, getByText } = render(
      <ResultsContent {...baseProps} scoring_v2={sv2} />
    );
    // No factual verdict → recommendation body shows instead.
    expect(queryByTestId('results-content-factual-verdict')).toBeNull();
    expect(getByText('Tuned to your priorities — camera + battery win')).toBeTruthy();
    // Runner-up caption STILL renders (it never depended on factual_verdict).
    expect(getByText('results.runnerUpWins')).toBeTruthy();
    expect(getByText(KEY_TRADEOFF)).toBeTruthy();
  });

  it('omits the runner-up caption only when key_tradeoff is absent', () => {
    const result = {
      ...baseProps.result,
      overview: {
        ...baseProps.result.overview,
        winner: { ...baseProps.result.overview.winner, key_tradeoff: undefined },
      },
    };
    const { queryByText, getByTestId } = render(
      <ResultsContent {...baseProps} result={result} />
    );
    // Factual verdict still shows; the caption is absent (no data to show).
    expect(getByTestId('results-content-factual-verdict')).toBeTruthy();
    expect(queryByText('results.runnerUpWins')).toBeNull();
  });
});
