"""UNIT A2 (U0.2b) / issue #94 — the 4 registry rows the 2026-08-25 bake-off
measured as WRONG stay corrected.

The bake-off (docs/investigations/2026-08-25-scraper-bakeoff.md) fetched 9
registry targets and found four bad rows in `data/bh_gcc_sources.json`:

  matalanme.com  flagged render-only, but plain curl prices it in <1s
  xcite.com      flagged render-only, but the price is in the STATIC HTML
  bfab.com       sample_url 308-redirects to a CATEGORY listing, not a PDP
  letoile.ae     sample_url is a dead 404

`data/bh_gcc_sources.json` is GENERATED by scripts/build_source_registry_data.py
from the four discovery catalogs, so a correction applied only to the generated
file is erased by the next rebuild. These tests pin BOTH ends — the catalog rows
that are the source of truth AND the generated rows — plus the two consolidation
behaviours that make the correction survive a rebuild (the stale `render-only`
status must not be carried onto a row that is no longer render-only, and the
measured probe record must be carried through).

Free + offline: every assertion reads a committed file or calls the pure
consolidation. No network, no vendor credits.
"""
import json

import pytest

from app.services import source_router as sr
from scripts import build_source_registry_data as build

# The corrected rows, as MEASURED 2026-08-30 by free curl_cffi and judged by the
# repo's own price_service.extract_price_from_html / fetch_page_price.
CORRECTED = {
    "matalanme.com": "https://www.matalanme.com/bh_en/sarong",
    "xcite.com": "https://www.xcite.com/apple-iphone-16-6-1-inch-128gb-black/p",
    "bfab.com": "https://bfab.com/bh_en/navy-collegiate-cap",
    "letoile.ae": (
        "https://letoile.ae/products/"
        "lancome_edp_la_vie_est_belle_spray_100_ml_klm999779"
    ),
}
# The two sample_urls the bake-off proved unusable — neither may come back.
RETIRED_SAMPLE_URLS = {
    "bfab.com": "https://bfab.com/bh_en/girls-gingham-dress",
    "letoile.ae": "https://letoile.ae/p/5-1-30-sxt000001",
}
PROBE_DATE = "2026-08-30"
_CATALOG = build._DATA / "bh_gcc_source_candidates_round2.json"


def _generated_rows():
    rows = json.loads(sr._CATALOG_DATA_PATH.read_text(encoding="utf-8"))
    return {r["domain"]: r for r in rows}


def _catalog_rows():
    rows = json.loads(_CATALOG.read_text(encoding="utf-8"))
    return {r["domain"]: r for r in rows}


# ---------------------------------------------------------------------------
# The GENERATED registry data (what source_router actually loads)
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("domain", sorted(CORRECTED))
def test_generated_row_is_not_render_only(domain):
    row = _generated_rows()[domain]
    assert row["is_render_only"] is False, (
        f"{domain} is flagged render-only, but free curl reads it — a false "
        "render-only routes a free page to the PAID render wave (#94)"
    )
    assert row["mechanism"] == "", f"{domain} should ride the plain curl page-scrape path"
    assert row["genuine_method"] == "page_scrape_jsonld"
    assert row["status"] != "render-only", (
        f"{domain} still carries the stale render-only STATUS — the consolidation "
        "merge must not preserve it once the row is no longer render-only"
    )


@pytest.mark.parametrize("domain,url", sorted(CORRECTED.items()))
def test_generated_row_sample_url_is_pinned(domain, url):
    assert _generated_rows()[domain]["sample_url"] == url


@pytest.mark.parametrize("domain,dead_url", sorted(RETIRED_SAMPLE_URLS.items()))
def test_retired_sample_urls_never_come_back(domain, dead_url):
    row = _generated_rows()[domain]
    assert row["sample_url"] != dead_url, (
        f"{domain} sample_url regressed to the unusable URL {dead_url}"
    )


@pytest.mark.parametrize("domain", sorted(CORRECTED))
def test_generated_row_carries_the_probe_record(domain):
    # Issue #94 item 5 — the probe date rides the row so the next reader knows
    # how stale the measurement is.
    measured = _generated_rows()[domain].get("measured", "")
    assert PROBE_DATE in measured, f"{domain} has no dated probe record: {measured!r}"


# ---------------------------------------------------------------------------
# The SOURCE OF TRUTH (the discovery catalog the generator reads)
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("domain,url", sorted(CORRECTED.items()))
def test_catalog_row_is_fixed_at_source(domain, url):
    row = _catalog_rows()[domain]
    assert row["mechanism"] != "render_required", (
        f"{domain} is still render_required in the CATALOG — a generated-file-only "
        "fix is erased by the next rebuild"
    )
    adapter = row["integration_adapter"].lower()
    assert "render tier" not in adapter and "firecrawl" not in adapter
    assert build._adapter_token(row["integration_adapter"]) == "fetch_page_price"
    assert row["sample_pdp_url"] == url
    assert PROBE_DATE in row.get("measured", "")


def test_rebuild_cannot_regress_the_corrected_rows():
    # The pure consolidation (no prior-file merge) must already produce the
    # corrected shape — this is what makes the fix survive a regeneration.
    rows = {r["domain"]: r for r in build.consolidate()}
    for domain, url in CORRECTED.items():
        r = rows[domain]
        assert r["is_render_only"] is False, domain
        assert r["mechanism"] == "", domain
        assert r["sample_url"] == url, domain
        assert PROBE_DATE in r.get("measured", ""), domain


# ---------------------------------------------------------------------------
# The consolidation behaviours the correction depends on
# ---------------------------------------------------------------------------

def test_merge_does_not_carry_stale_render_only_status():
    # THE TRAP: the idempotent merge preserves a prior status so the liveness
    # gate's verdict is never clobbered. A prior "render-only" is a verdict
    # ABOUT a render-only row — carrying it onto a row that is no longer
    # render-only would silently undo every flip this unit makes.
    rows = [{"domain": "x.com", "is_render_only": False,
             "status": "provider-test-candidate"}]
    build._merge_prior_verdicts(rows, {"x.com": {"status": "render-only"}})
    assert rows[0]["status"] == "provider-test-candidate"


def test_merge_still_preserves_render_only_for_a_still_render_row():
    rows = [{"domain": "y.com", "is_render_only": True,
             "status": "provider-test-candidate"}]
    build._merge_prior_verdicts(rows, {"y.com": {"status": "render-only"}})
    assert rows[0]["status"] == "render-only"


@pytest.mark.parametrize("status", ["live", "dead"])
def test_merge_preserves_liveness_verdicts_and_notes(status):
    rows = [{"domain": "z.com", "is_render_only": False,
             "status": "provider-test-candidate"}]
    build._merge_prior_verdicts(
        rows, {"z.com": {"status": status, "note": "demoted: non-retail"}}
    )
    assert rows[0]["status"] == status
    assert rows[0]["note"] == "demoted: non-retail"


def test_merge_preserves_dead_tombstones_the_generator_no_longer_emits():
    # Four demotions were followed by a generator SKIP and a fifth domain became
    # a registry literal, so a plain re-consolidation drops all five rows — and
    # with them the "Do not re-promote" rationale. A rebuild must not silently
    # delete a demotion record.
    rows = [{"domain": "kept.com", "tier": "bahrain", "priority_rank": 1,
             "is_render_only": False, "status": "live"}]
    merged = build._merge_prior_verdicts(rows, {
        "kept.com": {"status": "live"},
        "gone.com": {"domain": "gone.com", "tier": "bahrain", "priority_rank": 2,
                     "status": "dead", "note": "non-retail. Do not re-promote."},
    })
    by_domain = {r["domain"]: r for r in merged}
    assert by_domain["gone.com"]["note"].endswith("Do not re-promote.")
    assert [r["domain"] for r in merged] == ["kept.com", "gone.com"]  # re-sorted


def test_merge_does_not_resurrect_a_dropped_live_row():
    # Only DEAD tombstones survive: a live row the catalogs no longer carry is a
    # deliberate removal, and resurrecting it would re-admit a dropped source.
    rows = [{"domain": "kept.com", "tier": "bahrain", "priority_rank": 1,
             "is_render_only": False, "status": "live"}]
    merged = build._merge_prior_verdicts(rows, {
        "dropped.com": {"domain": "dropped.com", "tier": "bahrain",
                        "priority_rank": 2, "status": "live"},
    })
    assert [r["domain"] for r in merged] == ["kept.com"]


def test_rebuild_drops_no_row_and_touches_only_the_corrected_ones():
    # THE BLAST-RADIUS GATE the unit is judged on: regenerating against the
    # committed file as prior must reproduce it row-for-row.
    committed = json.loads(sr._CATALOG_DATA_PATH.read_text(encoding="utf-8"))
    prior = {r["domain"]: r for r in committed}
    rebuilt = build._merge_prior_verdicts(build.consolidate(), prior)
    assert [r["domain"] for r in rebuilt] == [r["domain"] for r in committed]
    assert rebuilt == committed, "a rebuild would change the committed registry data"


def test_measured_probe_record_is_carried_from_catalog_to_generated_row():
    row = {"domain": "q.bh", "integration_adapter": "fetch_page_price (mechanism=curl)",
           "mechanism": "curl_jsonld", "currency": "BHD", "country": "BH",
           "categories": ["fashion"], "sample_pdp_url": "https://q.bh/p/1",
           "priority_rank": 7, "measured": "2026-08-30 curl: 200, 1.000 BHD"}
    assert build._measured_note(row) == "2026-08-30 curl: 200, 1.000 BHD"
    assert build._measured_note({"domain": "q.bh"}) == ""


def test_liveness_gate_domain_filter_probes_only_the_named_rows():
    # `--domain` is what let this unit re-verdict the four corrected rows
    # without re-probing (and re-writing) all 368. Without it the correction's
    # diff is unreviewable.
    import asyncio

    from scripts import verify_bh_gcc_sources as verify

    probed = []

    async def _fake_probe(url, mechanism=""):
        probed.append(url)
        return "live", "http=200 +price"

    real_probe = verify._probe
    verify._probe = _fake_probe
    try:
        rows = [
            {"domain": "wanted.com", "tier": "gcc", "mechanism": "",
             "sample_url": "https://wanted.com/p/1", "is_render_only": False,
             "status": "provider-test-candidate"},
            {"domain": "www.other.com", "tier": "gcc", "mechanism": "",
             "sample_url": "https://other.com/p/1", "is_render_only": False,
             "status": "provider-test-candidate"},
        ]
        tally = asyncio.run(verify._run(rows, None, None, {"wanted.com"}))
    finally:
        verify._probe = real_probe
    assert probed == ["https://wanted.com/p/1"]
    assert tally["live"] == 1
    assert rows[0]["status"] == "live"
    assert rows[1]["status"] == "provider-test-candidate"  # untouched


def test_liveness_gate_domain_filter_is_www_insensitive():
    from scripts import verify_bh_gcc_sources as verify

    assert verify._norm_domain("WWW.Bfab.com ") == "bfab.com"
    assert verify._norm_domain(None) == ""


def test_no_other_generated_row_gained_a_probe_record():
    # Blast-radius pin: the rebuild must have touched ONLY the intended rows.
    rows = json.loads(sr._CATALOG_DATA_PATH.read_text(encoding="utf-8"))
    with_measured = {r["domain"] for r in rows if r.get("measured")}
    assert with_measured == set(CORRECTED)
