import json, pathlib
SP = pathlib.Path(__file__).resolve().parent
H = json.load(open(SP / 'heads_extra.json', encoding='utf-8'))
H["R-W04"] = {
 "title": "retro(price): R-W04 - every price parse offloads to a bounded price-parse pool under ENABLE_PRICE_PARSE_OFFLOAD, fetches capped at 3 MB, harness --flags-on/--compare",
 "subject": "retro(price): W0-4b 3 MB fetch cap, W0-4c the six remaining inline parse sites offloaded + AST guard, W0-4d bounded price-parse pool with a per-loop submission semaphore, harness --flags-on/--compare",
 "units": "W0-4 parse-once offload (#135, merged in session 65 without review)",
 "facts": (
  "**Everything sits inside the EXISTING `ENABLE_PRICE_PARSE_OFFLOAD` (default OFF, read per call; no new flag). Flag OFF is byte-identical to base**, measured on the frozen corpus (OFF `OVERALL 9504e5a9...`, results `a1b3460c...`, equal to a same-environment `origin/main` run) and by the 289-file comm gate (base == head: only the two `test_page_scraping` baseline ids); flag ON `--compare` OFF: **0 of 1,656 records differ** with the cap in place; 11 corpus records exceed 3,000,000 chars and none moves under the cap (0/88 comparisons).\n\n"
  "**Verdict:** the session-66 red was KILLED mid-run; session 67 resumed it (44 right-reason reds / 59 pins, satisfiability proven with a prototype green on a scratch `origin/main` worktree) -> Fable gate (the sixth site `StructuredComparisonService._fetch_page_price` stays in scope; `copy_context().run` mandatory; the semaphore is a SUBMISSION-DEPTH contract acquired before submit and created per event loop) -> green (112 unit nodes in both flag states; 32/32 mutants killed incl. the reviewer's M6 lxml-when-ON and the prototype variants; comm 289 files 11,093 passed / the 2 baseline failures) -> adversary r0 SOUND (no code defect, 6 prove-nothing rows) -> fix (test-only: every round-0 survivor killed) -> adversary r1 **SOUND** (5 minor test-side notes, no code defect).\n\n"
  "**What the flag now does ON (as amended):** `curl_fetch_html` and the firecrawl / scrapedo render legs hand at most `PRICE_FETCH_MAX_BYTES` = 3,000,000 chars to the parse (mirroring `curl_fetch_html_same_site`; the provider-attempt `html_kb` telemetry keeps the raw body size in both states); the six sites that still parsed INLINE on the event loop - `fetch_iherb_price`, `fetch_bolo_price`, `fetch_boutiqaat_price`, `_try_pharmacy_urls`, `url_extraction_service.extract_with_ai`, `StructuredComparisonService._fetch_page_price` (the earlier CLAUDE.md sentence that iHerb 'already parses inside a run_in_executor lambda' was FALSE) - each move their pure-sync parse block into ONE offload call; every offloaded parse (the three original sites too) runs on a dedicated `ThreadPoolExecutor(thread_name_prefix='price-parse')` sized by `PRICE_PARSE_MAX_WORKERS` (default 4, clamped 1..16; unparsable, empty and non-finite fall back to 4; read once when the pool is built) behind a per-event-loop `asyncio.Semaphore` of the same size acquired BEFORE submit (queued parses wait in asyncio, cancellable, never in the executor's work queue), entered through `contextvars.copy_context().run` so the resolved-category ContextVar reaches the worker (a bare `run_in_executor` fails 9 ContextVar pins); a source-level AST guard keeps the inline-parse allowlist EMPTY. Harness: `scripts/verify_flag_byte_identity.py --flags-on <flags>` (restores the prior env, including unset) and `--compare <other-results.json>` (results-array sha equality + the first differing records, exit 1 on mismatch, occurrence-keyed).\n\n"
  "**Measured residual (the reviewer's minor defect, now bounded, not removed):** offloaded real parses of the largest (3.9-4.1 MB) corpus pages still cost the loop 35-143 ms single and 171-534 ms with six at once (six median pages 142-174 ms) against 1,089 ms inline; the CPU-bound heartbeat bound holds at the three shipped sites (~32 ms, the Windows timer floor) and is pinned at all nine.\n\n"
  "**Stated limits / follow-ups:** W0-4e - under the flag the 3 MB cap also bounds `structured_comparison_service._lazy_bh_pdp_backfill`'s regex scan of a curled search page (an href past 3,000,000 chars is no longer found; pinned flag-OFF only); W0-4f - `url_extraction_service.extract_from_url`'s three soups (`extract_amazon_data` / `extract_noon_data` / `extract_generic_data`) still build on the loop (allowlisted in the transitive AST test); the corpus harness cannot observe the cap (it calls `extract_price_from_html` directly); five over-cap files on disk are unresolved by the manifest (3.15-3.96 M chars plus one 10.48 M DACH page); the r1 adversary's five test-side notes (the reader tested with 'true' only at one site; a 4,000-char text-truncation blind spot in the extract_with_ai prompt pin; two harness `--compare` edge cases unpinned; two equivalent mutants) - test-hardening follow-up W0-4g.\n\n"
  "**CLAUDE.md corrections carried by the docs PR:** delete the '50 ms heartbeat ticked 0 times' claim and the false iHerb sentence in the W0-4 row; activation step (2) gains the pool sizing + queue-depth / `loop_lag_ms` watch and the residual.\n"
 ),
 "msg": (
  "Retro-fix group R-W04 for W0-4 (#135). Inside ENABLE_PRICE_PARSE_OFFLOAD (default OFF); flag OFF byte-identical on the corpus\n"
  "(OFF OVERALL 9504e5a9 / results a1b3460c == same-env origin/main; ON --compare OFF 0/1656 differ) and on the 289-file comm set.\n"
  "- W0-4b: curl_fetch_html and the firecrawl/scrapedo render legs cap the parse input at PRICE_FETCH_MAX_BYTES = 3_000_000\n  (html_kb telemetry keeps the raw body); 11 corpus records exceed the cap, none moves.\n"
  "- W0-4c: fetch_iherb_price, fetch_bolo_price, fetch_boutiqaat_price, _try_pharmacy_urls, extract_with_ai and\n  StructuredComparisonService._fetch_page_price move their pure-sync parse block into ONE offload call (flag OFF keeps the\n  inline code verbatim); a source-level AST guard keeps the inline-parse allowlist empty.\n"
  "- W0-4d: every offloaded parse runs on a dedicated 'price-parse' ThreadPoolExecutor (PRICE_PARSE_MAX_WORKERS, default 4,\n  clamped 1..16) behind a per-event-loop asyncio.Semaphore of the same size acquired before submit, entered through\n  contextvars.copy_context().run; pins for saturation, cancellation, thread names, pool size and a CPU-bound gap bound.\n"
  "- Harness: scripts/verify_flag_byte_identity.py gains --flags-on (env restored) and --compare (results-array sha equality).\n"
  "Tests: 112 unit nodes both flag states; site files green (2 baseline ids); 289-file comm base == head; 32/32 mutants killed;\n"
  "adversary r0 SOUND, r1 SOUND."
 ),
}
json.dump(H, open(SP / 'heads_extra.json', 'w', encoding='utf-8'), indent=1, ensure_ascii=False)
print("R-W04 header staged; heads:", list(H.keys()))
