import json, shutil, pathlib
SP = pathlib.Path(__file__).resolve().parent
H = json.load(open(SP / 'heads_extra.json', encoding='utf-8'))
H["R-METER"] = {
 "title": "retro(api): R-METER - a failed camera comparison is a non-delivery under metering (refund, no lifetime bump, no history), a failed URL verdict never ships raw exception text, anon credits are refunded on every non-delivery exit",
 "subject": "retro(api): W2-1b camera unsuccessful result = non-delivery under ENABLE_PAID_ROUTE_METERING (+ ENABLE_CAMERA_FAILURE_ENVELOPE), W2-1c /url/compare failed verdict -> 503 LLM_UNAVAILABLE never str(e), W2-1d anon refunds on the six exits",
 "units": "W2-1 paid-route metering (#137, merged in session 65 without review)",
 "facts": (
  "**Verdict trail (the longest of the wave):** session-66 adversary r0 SOUND (5 minors, fix round killed) -> session-67 adversary r1 SOUND (4 minors, 8 prove-nothing rows) -> fix -> adversary r2 DEFECTIVE (major test gap: no ledger pin in the both-flags-ON deploy state; the presence check pinned instead of the ruled truthiness) -> fix r3 (truthiness; 10 both-flags-ON ledger pins; BASE/GREEN pin labels) -> adversary r3 DEFECTIVE on a REBASE-COMPOSITION defect (main now carries W4-9's codeless-message allowlist in `text_routes._surface_comparison_failure`, so routing the code-less <2-products `/url/compare` exit through it would have redacted its body) -> the branch was rebased onto `db1ed3a4` and fix r4 routes ONLY a coded failure through that mapping while the code-less exit keeps main's exact bare-string 400 (two mutants pin the fork) -> adversary r4 **SOUND** (2 documentation / latent-contract minors).\n\n"
  "**Flags:** NEW `ENABLE_CAMERA_FAILURE_ENVELOPE` (default OFF, per call; `image_routes.camera_failure_envelope_enabled`) - ON: an UNSUCCESSFUL camera comparison returns the `comparison_failed` envelope exit 6 already ships (the 97b5f15 client falls back to text) carrying the result's own code; OFF: today's `action: \"comparison\"` body. The no-bill half sits inside the EXISTING `ENABLE_PAID_ROUTE_METERING`: an unsuccessful result is a NON-delivery (reserved credit refunded, anon credit refunded once, no `record_lifetime_comparison`, no history row, `log_search success=False`) - pinned in the both-flags-ON state the operators will deploy. **Flip both together**: envelope ON + metering OFF still logs success and writes history (pinned, by design). **Unflagged (live leaks with no legitimate reader):** a code-less unsuccessful camera result's `error` (compare_from_text's `str(e)`, measured carrying an OpenAI key tail) is replaced by the constant `comparison unavailable` (M13-26 class); `compare_from_urls` no longer delivers a verdict that carries a non-empty `error` (generate_comparison's except-branch: `success: True` with a fabricated winner_index 0 and the raw exception text) - it returns `{success: False, code: LLM_UNAVAILABLE}` and the route ships **503** with the constant message (decided: the text route's mapping is the contract; ruling 3's literal 400 was the contradiction); a falsy `error` (None / '') is delivered exactly as base (pinned from deep copies).\n\n"
  "**Gates:** 132 unit nodes (`tests/test_retro_w2_1.py` + `tests/test_paid_route_metering.py`) green in six ambient flag states under a process-wide socket guard; base classification at `db1ed3a4`: 27 RED fail, 42 BASE PINs pass, 40 GREEN PINs fail, 0 mislabelled; 75 mutants: 67 killed, 7 benign equivalents, incl. the both-flags fall-through / skip-refund / envelope-before-refund / log-success mutants and the four in-place verdict mutants; comm gate over the recorded 17-file set with the base a detached worktree of `db1ed3a4`: identical failed sets (the three #89 camera_vision ids + the DNS-dependent `test_detect_allows_valid_url` under the guard).\n\n"
  "**Recorded, not built (issue #128 follow-ups):** `/url/compare` has NO anonymous gate; the anon credit on `/image/identify` is debited BEFORE the five image-validation 400s and the moderation re-raise, which are not refunded. **Latent contract note (r4 minor):** the route now maps ANY coded non-success through the text route's mapping; `compare_from_urls` produces exactly one coded failure today (LLM_UNAVAILABLE); a future TIMEOUT / INSUFFICIENT_DATA / CONTENT_UNAVAILABLE result would take that mapping's status (503 / 400 / 200) instead of the bare 400 - stated here as the mapping's contract.\n"
 ),
 "msg": (
  "Retro-fix group R-METER for W2-1 (#137).\n"
  "- W2-1b: the camera route reads compare_from_text's success flag. Inside ENABLE_PAID_ROUTE_METERING an unsuccessful result is a\n  NON-delivery: refund the reserved credit, refund the anon credit once, no lifetime bump, no history row, log_search\n  success=False (pinned in the both-flags-ON state). Inside the NEW ENABLE_CAMERA_FAILURE_ENVELOPE (default OFF) the body\n  is the comparison_failed envelope exit 6 already ships; OFF keeps today's action=comparison body. Unflagged: a code-less\n  failure's error (str(e), measured with an OpenAI key tail) becomes the constant 'comparison unavailable'.\n"
  "- W2-1c (unflagged): compare_from_urls returns success False / LLM_UNAVAILABLE / constant message when the verdict carries a\n  non-empty error (truthiness, composes with W4-9's constant); the route ships 503 through the text route's mapping ONLY for\n  a coded failure - the code-less <2-products exit keeps main's bare-string 400 (W4-9's allowlist would redact it).\n"
  "- W2-1d: refund_anon_comparison_credit wired on the six non-delivery exits + the new exit 7 under the metering flag;\n  /url/compare's missing anon gate and the pre-validation anon debit are recorded for #128, not built.\n"
  "Tests: 132 nodes x 6 ambient states; 17-file comm set base(db1ed3a4) == head; 67/75 mutants killed; adversary r4 SOUND."
 ),
}
json.dump(H, open(SP / 'heads_extra.json', 'w', encoding='utf-8'), indent=1, ensure_ascii=False)
shutil.copy(SP / 'retro_fix_r4_R-METER.json', SP / 'retro_fix_r1_R-METER.json')
shutil.copy(SP / 'retro_adv_R-METER_r4.json', SP / 'retro_adv_R-METER_r1.json')
print("R-METER header + final reports staged; heads:", list(H.keys()))
