"""Assemble the W4-14 PR body: the final fixer's pr_text + Fable's ship addendum, attribution last."""
import io
NSP = "C:/Users/SynAckITPC/AppData/Local/Temp/claude/C--Users-SynAckITPC-Documents-AI/0a2845de-abfe-4bca-b433-df4ce9787ab5/scratchpad"
src = io.open(NSP + "/pr_text_w4_14_final.md", encoding="utf-8").read().rstrip()
ATTR = "\U0001F916 Generated with [Claude Code](https://claude.com/claude-code)"
if src.endswith(ATTR):
    src = src[: -len(ATTR)].rstrip()
addendum = """
### Orchestrator addendum (Fable, ship time 2026-09-27)
- **Pipeline (one green, three adversaries, two fix rounds, all bounded):** red at `3985eaac` (28 RED / 14 PIN / 21 KILL; the satisfiability prototype green on every gate incl. the full jest suite) -> Fable red-gate rulings R1-R11 -> green (the prototype's design with R2 / R8) -> adversary r0 SOUND (3 minors) -> fix r1 (tests only) -> adversary r1 SOUND (3 minors) -> fix r2 (tests only) -> adversary r2 SOUND (3 minors). The nine production files are sha-identical to the green's bytes at every later round; every adversary left the worktree byte-identical to the reported shas. Rulings: `.qa-s68/specs/W4_14_FABLE_RULINGS.md` (+ the red-gate section) and `W4_14_LAUNCH_NOTES.md`, archived in the session state folder.
- **Adversary r2's three pin gaps closed by the orchestrator (test rows only, no app change):** (1) `test_38` gains the unrecognised-value rows (`2`, `enabled`, `y`, `t`, `tru` read as OFF; `TRUE`, `On`, ` yes ` as ON) - a reader rewritten as "anything not falsy" reddens 5 nodes; (2) the capture harness can return the RESULT and the new `test_40` pins that the `(comparison, usage)` `generate_comparison` returns is identical for `output_lang` None / en / ar with the flag OFF and for None / en with it ON, and that flag ON + ar changes the prompt only - an output-side fork (`parsed["winner_reason"] = "AR"` after the JSON parse, no flag check) reddens 3 nodes; (3) `referralExpiryPlurals.w414` gains the `_two` / `_few` / `_many` pin by value with the Arabic rendering at counts 2, 3 and 11 - the hours `_zero` copy moved into `_two` reddens the suite. Every restore sha-verified. The backend unit file grows 209 -> 226 nodes (230 with the parity fence); the plural suite 2 -> 3 tests.
- **Correction to the pr_text above (fix r1's finding, lost in the round-2 rewrite):** `/url/compare` HAS a live client caller - HomeScreen's Link mode (`handleUrlCompare`) posts to it, and `url_extraction_service` calls `generate_comparison` without `output_lang` - so Link-mode Arabic users AND camera users (`/image/identify`) keep English verdicts even with the flag ON until W4-14b. The spec review's R2.7 route inventory and ruling Q3 were wrong on this point; read the stated limit "`/image/identify` gets no `lang`" as "`/url/compare` and `/image/identify` get no `lang`", and the W4-14b follow-up covers both routes.
- **Post-rebase ship checks on `d3516a40`** (onto main `3424da3c`, a docs-only move since the unit base): the backend unit files 230 passed in each of the five states (unset / ARABIC / ARABIC+PROMPT_TRUTH / PROMPT_TRUTH / ARABIC+COHORT); the backend CI-order set (15 files, one process) 443 passed in the unset and flag-ON states with the netguard ratchet OK (18 attempting nodes, every one in the 205-node baseline); ruff E9,F63,F7,F82 and py_compile clean; the must-not-touch gate empty (`prompt_personalities.py`, `response_builder.py`, `scoring_service.py`, the W4-11 digest fixture, the netguard baseline, `tests/.pre_impl_failures.txt`, `formatNumber.ts`, `currencyDisplay.ts`, `ResultsContent.tsx`, `HistoryScreen.tsx`, `ResultsAccordion.tsx`, `PersonalizationChip.tsx`, `CategoryProfile.tsx`, `_deltaText.ts`, `app.json`, `eas.json`, the package files - all untouched) and no `.snap` moved; the client CI-order set 18 suites / 134 tests / 4 snapshots; the FULL jest suite 328 passed + 3 skipped suites, 3177 tests, **44/44 snapshots**, no `-u`; tsc 5.9.3 `--noEmit` exit 0; eslint 0 errors (148 warnings, the pre-unit count). The `scripts/verify_flag_byte_identity.py` price-corpus harness is not applicable (no price code moves).
- **Flags on main after this merge (default OFF, read per call):** `ENABLE_ARABIC_VERDICT_OUTPUT`. Nothing is flipped; Railway and Supabase untouched. The client half is main-only until the next `eas update --branch preview --clear-cache` (Ahmed's lever), after the native review of the 51 Arabic labels. Follow-ups filed after the merge: W4-14b (PersonalizationChip `dim_key` + `lang` on `/url/compare` and `/image/identify`), W4-14c (the flip's hard precondition), W4-14d (`delta_text` + the factual verdict lines as key+params), W4-14e (`compareTextPair`), and the `category_switched` DECISIONS item for Ahmed.
"""
out = src + "\n" + addendum.rstrip() + "\n\n" + ATTR + "\n"
io.open(NSP + "/prbody_w4_14.md", "w", encoding="utf-8", newline="\n").write(out)
print("wrote prbody_w4_14.md", len(out), "chars; url/compare mentions:", out.count("url/compare"))
