"""Network-attempt ratchet over a netguard report (issue #184).

    python scripts/netguard_ratchet.py REPORT [BASELINE] [--write]

REPORT is the JSON ``tests/_netguard.py`` writes when ``QAREN_NETGUARD_REPORT`` is set:
``{"blocked": n, "nodes": {nodeid: [targets]}, "classes": {nodeid: [classes]}}``.
BASELINE defaults to ``tests/.network_attempt_baseline.txt``: one ``<nodeid> <classes>``
line per attempting test (classes comma-joined from ``sentinel`` / ``ip_literal`` /
``egress``), sorted, ``#`` comments allowed. It is GENERATED -- never hand-edited -- by
this script with ``--write``.

Exit codes:
  0  every attempting node is in the baseline (a shrink is printed), or the only new
     nodes attempt ``sentinel`` / ``ip_literal`` hosts (printed as WARNING lines); a
     baseline node that gained a class (e.g. sentinel -> sentinel,egress) is also a
     WARNING line, not a failure (R7 fails only on a NEW node id);
  1  a NEW node id whose classes include ``egress`` (printed);
  2  the report (or the baseline) is missing or unreadable.
The ``<collection>`` pseudo-node (attempts at import/collection/session time) never
fails the ratchet. A node without a ``classes`` entry is classified from its targets.
"""
import argparse
import ipaddress
import json
import sys
from pathlib import Path
from urllib.parse import urlsplit

DEFAULT_BASELINE = Path(__file__).resolve().parent.parent / "tests" / ".network_attempt_baseline.txt"
COLLECTION_NODE = "<collection>"
CLASSES = ("sentinel", "ip_literal", "egress")
HEADER = (
    "# GENERATED by scripts/netguard_ratchet.py --write -- never hand-edit.\n"
    "# One '<nodeid> <classes>' line per free-tier test that attempted the network under\n"
    "# tests/_netguard.py (sentinel = *.invalid / neutralized.* credential placeholders,\n"
    "# ip_literal = a numeric host, egress = anything else). CI fails on a NEW node whose\n"
    "# classes include egress; shrinking this list is the follow-up campaign.\n"
)


def _classify_target(target):
    """Fallback for a report without ``classes``: 'kind host[:port]' or 'kind url'."""
    text = str(target).split(" ", 1)[-1]
    if "://" in text:
        host = urlsplit(text).hostname or ""
    elif text.startswith("["):
        host = text[1:text.find("]")]
    else:
        host = text.rsplit(":", 1)[0] if ":" in text else text
    host = host.strip().lower()
    if host.endswith(".invalid") or host.startswith("neutralized."):
        return "sentinel"
    try:
        ipaddress.ip_address(host)
        return "ip_literal"
    except ValueError:
        return "egress"


def load_report(path):
    """``{nodeid: set(classes)}`` from a report, without the ``<collection>`` node."""
    data = json.loads(Path(path).read_text(encoding="utf-8"))
    nodes = data["nodes"]
    classes = data.get("classes") or {}
    out = {}
    for nodeid, targets in nodes.items():
        if nodeid == COLLECTION_NODE:
            continue
        cls = classes.get(nodeid)
        out[nodeid] = set(cls) if cls else {_classify_target(t) for t in targets}
    return out


def load_baseline(path):
    """``{nodeid: set(classes)}`` from a baseline (a bare id line carries no classes)."""
    out = {}
    for line in Path(path).read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        nodeid, _, tail = line.rpartition(" ")
        if nodeid and tail and all(c in CLASSES for c in tail.split(",")):
            out[nodeid] = set(tail.split(","))
        else:
            out[line] = set()
    return out


def write_baseline(path, nodes):
    lines = ["%s %s\n" % (n, ",".join(c for c in CLASSES if c in nodes[n])) for n in sorted(nodes)]
    Path(path).write_text(HEADER + "".join(lines), encoding="utf-8", newline="\n")


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("report")
    ap.add_argument("baseline", nargs="?", default=str(DEFAULT_BASELINE))
    ap.add_argument("--write", action="store_true", help="regenerate the baseline from the report")
    args = ap.parse_args(argv)

    try:
        current = load_report(args.report)
    except (OSError, ValueError, KeyError, TypeError, AttributeError) as exc:
        print("[netguard-ratchet] cannot read report %s: %s" % (args.report, type(exc).__name__))
        return 2
    if args.write:
        write_baseline(args.baseline, current)
        print("[netguard-ratchet] wrote %d node(s) to %s" % (len(current), args.baseline))
        return 0
    try:
        baseline = load_baseline(args.baseline)
    except OSError as exc:
        print("[netguard-ratchet] cannot read baseline %s: %s" % (args.baseline, type(exc).__name__))
        return 2

    new = sorted(set(current) - set(baseline))
    new_egress = [n for n in new if "egress" in current[n]]
    for nodeid in sorted(set(baseline) - set(current)):
        print("[netguard-ratchet] shrink: %s no longer attempts the network "
              "(regenerate the baseline with --write)" % nodeid)
    for nodeid in sorted(set(current) & set(baseline)):
        grown = current[nodeid] - baseline[nodeid]
        if baseline[nodeid] and grown:
            print("[netguard-ratchet] WARNING: baseline node %s now also attempts %s hosts "
                  "(baseline: %s); fix the test or regenerate the baseline with --write"
                  % (nodeid, ",".join(sorted(grown)), ",".join(sorted(baseline[nodeid]))))
    for nodeid in new:
        if nodeid not in new_egress:
            print("[netguard-ratchet] WARNING: new node %s attempts %s hosts only (allowed for now)"
                  % (nodeid, ",".join(sorted(current[nodeid]))))
    for nodeid in new_egress:
        print("[netguard-ratchet] NEW: %s attempts the network (%s)"
              % (nodeid, ",".join(sorted(current[nodeid]))))
    if new_egress:
        print("[netguard-ratchet] FAIL: %d new node(s) attempt real egress; mock the call "
              "(tests/_netguard.py blocks it anyway) instead of growing the baseline" % len(new_egress))
        return 1
    print("[netguard-ratchet] OK: %d attempting node(s), baseline %d" % (len(current), len(baseline)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
